name: dart_sse_client
description: A package that helps you to receive server-sent messages the using the Server-Sent Events (SSE) mechanism.
version: 3.0.0
homepage: https://github.com/pratikbaid3/flutter_client_sse

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  http: ^1.2.0
  async: ^2.11.0

dev_dependencies:
  test: ^1.24.9
